### ISSUE TITLE
Zusatztafel-Bilder

### ISSUE THREAD

**Issue by wolfgang-8** [Luzandro/roadsignpresetAT#1]
Anbei die im [Beispiel](https://community.openstreetmap.org/t/at-preset-fur-josm-verkehrszeichenerweiterung/108245/8) von mir veränderten Zusatztafel-Bilder zur Integration ins Preset:

![Zusatztafel_ausgenommen_Radfahrer](https://github.com/Luzandro/roadsignpresetAT/assets/105060323/2cce17f4-3d74-4526-a4fd-bbe2dd072441)
![Zusatztafel_hgv_conditional](https://github.com/Luzandro/roadsignpresetAT/assets/105060323/25a572c6-d259-42c3-bf46-a12cf2dfc16d)
![Zusatztafel_text](https://github.com/Luzandro/roadsignpresetAT/assets/105060323/a5ad231a-c192-4ca9-b219-f6e415da9de6)

**Comment by Luzandro** [comment]
Danke, habs integriert
